--- arch/x86_64/Makefile
+++ arch/x86_64/Makefile
@@ -30,6 +30,7 @@
 cflags-kernel-y	:=
 cflags-$(CONFIG_MK8) += $(call cc-option,-march=k8)
 cflags-$(CONFIG_MPSC) += $(call cc-option,-march=nocona)
+cflags-$(CONFIG_KDB) += $(call cc-option,-fno-optimize-sibling-calls,)
 # gcc doesn't support -march=core2 yet as of gcc 4.3, but I hope it
 # will eventually. Use -mtune=generic as fallback
 cflags-$(CONFIG_MCORE2) += \
@@ -80,6 +81,7 @@
 core-$(CONFIG_IA32_EMULATION)		+= arch/x86_64/ia32/
 drivers-$(CONFIG_PCI)			+= arch/x86_64/pci/
 drivers-$(CONFIG_OPROFILE)		+= arch/x86_64/oprofile/
+drivers-$(CONFIG_KDB)			+= arch/x86_64/kdb/
 
 boot := arch/x86_64/boot
 
